# Generated by Django 4.1.3 on 2024-03-25 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('salary', models.CharField(max_length=64, verbose_name='З/п')),
                ('field_activity', models.CharField(max_length=64, verbose_name='Сфера деятельности')),
                ('schedule', models.CharField(max_length=64, verbose_name='График работы')),
                ('payments', models.CharField(max_length=64, verbose_name='Частота выплат')),
                ('experience', models.CharField(max_length=64, verbose_name='Опыт работы')),
                ('including_for', models.CharField(max_length=256, verbose_name='В том числе для кандидатов')),
                ('inventory', models.CharField(max_length=256, verbose_name='Что получают работники')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
