# Generated by Django 4.1.3 on 2024-03-31 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_alter_vacancies_date_alter_vacancies_employer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryVacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Навзвание')),
            ],
            options={
                'verbose_name': 'Категория вакансий',
                'verbose_name_plural': 'Категории вакансий',
            },
        ),
        migrations.RemoveField(
            model_name='vacancies',
            name='field_activity',
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vacancies.categoryvacancies', verbose_name='Категория'),
        ),
    ]
