# Generated by Django 4.1.3 on 2024-03-31 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_categoryvacancies_remove_vacancies_field_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='salary',
            field=models.IntegerField(verbose_name='З/п'),
        ),
    ]
