# Generated by Django 4.1.3 on 2024-03-29 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_alter_vacancies_date_alter_vacancies_employer_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='applications.status', verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='application',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='application',
            name='vacancies_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancies', verbose_name='Вакансия'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Текст комметария')),
                ('date', models.DateTimeField(default='2024-03-28 01:12', verbose_name='Дата публикации')),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application', verbose_name='Заявка')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
